apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: create-myopenshiftblog-namespace
policyDefaults:
  namespace: policies
  remediationAction: inform
  placement:
    labelSelector:
      matchExpressions:
      - key: environment
        operator: In
        values:
        - prod
policies:
  - name: create-myopenshiftblog-namespace
    manifests:
      - path: myopenshiftblog-ns.yaml
